{% set name = "pyprof2calltree" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a635672ff31677486350b2be9a823ef92f740e6354a6aeda8fa4a8a3768e8f2f

build:
  number: 0
  noarch: python
  entry_points:
    - pyprof2calltree = pyprof2calltree:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  commands:
    - pyprof2calltree --help

about:
  home: https://github.com/pwaller/pyprof2calltree/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Help visualize profiling data from cProfile with kcachegrind and qcachegrind

extra:
  recipe-maintainers:
    - xhochy
